#pragma once

#define UPLOAD_DIRECTORY "/Uploaded_files"

#define CLIENT "CLIENT"
#define MAIN_SERVER "MAIN_SERVER"
#define REPLICA "REPLICA"

#define RESPONSE_DOWNLOAD_READY "DOWNLOAD_READY"
#define RESPONSE_DOWNLOAD_FAILED "DOWNLOAD_FAILED"
#define RESPONSE_DELETE_SUCCESS "DELETE_SUCCESS"
#define RESPONSE_DELETE_FAILED "DELETE_FAILED"
#define RESPONSE_UPLOAD_SUCCESS "UPLOAD_SUCCESS"
#define RESPONSE_UPLOAD_FAILED "UPLOAD_FAILED"
#define RESPONSE_READY_FOR_DATA "READY_FOR_DATA"
#define RESPONSE_CHUNK_RECEIVED "CHUNK_RECEIVED"

#define COMMAND_LOGIN "LOGIN"
#define COMMAND_REGISTER "REGISTER"
#define COMMAND_DOWNLOAD "DOWNLOAD"
#define COMMAND_UPLOAD "UPLOAD"
#define COMMAND_UPLOAD_CHUNK "UPLOAD_CHUNK"
#define COMMAND_DELETE "DELETE"
#define COMMAND_REPLICA_UPLOAD "REPLICA_UPLOAD"
#define COMMAND_REPLICA_DELETE "REPLICA_DELETE"
#define COMMAND_REPLICA_DOWNLOAD "REPLICA_DOWNLOAD"

#define CHUNK_SIZE 1024
