#pragma once

#define DATABASE_TYPE "QSQLITE"
#define DATABASE_NAME "db.db"

#define UPLOAD_DIRECTORY "/Uploaded_files"

#define RESPONSE_LOGIN_SUCCESS "LOGIN_SUCCESS"
#define RESPONSE_LOGIN_FAILED "LOGIN_FAILED"
#define RESPONSE_REGISTER_SUCCESS "REGISTER_SUCCESS"
#define RESPONSE_REGISTER_USER_EXISTS "REGISTER_USER_EXISTS"
#define RESPONSE_REGISTER_FAILED "REGISTER_FAILED"
#define RESPONSE_DOWNLOAD_READY "DOWNLOAD_READY"
#define RESPONSE_DOWNLOAD_FAILED "DOWNLOAD_FAILED"
#define RESPONSE_DELETE_SUCCESS "DELETE_SUCCESS"
#define RESPONSE_DELETE_FAILED "DELETE_FAILED"
#define RESPONSE_UPLOAD_SUCCESS "UPLOAD_SUCCESS"
#define RESPONSE_UPLOAD_FAILED "UPLOAD_FAILED"
#define RESPONSE_READY_FOR_DATA "READY_FOR_DATA"
#define RESPONSE_CHUNK_RECEIVED "CHUNK_RECEIVED"
#define RESPONSE_FILES_LIST "FILES_LIST"

#define COMMAND_LOGIN "LOGIN"
#define COMMAND_REGISTER "REGISTER"
#define COMMAND_DOWNLOAD "DOWNLOAD"
#define COMMAND_UPLOAD "UPLOAD"
#define COMMAND_DELETE "DELETE"
#define COMMAND_GET_FILES "GET_FILES"

#define CHUNK_SIZE 1024

#define TABLE_USERS "users"
#define FIELD_USER_ID "id"
#define FIELD_USER_USERNAME "username"
#define FIELD_USER_PASSWORD "password"

#define TABLE_FILES "files"
#define FIELD_FILE_ID "id"
#define FIELD_FILE_FILENAME "file_name"
#define FIELD_FILE_OWNER "owner"
#define FIELD_FILE_SIZE "size"
#define FIELD_FILE_UPLOAD_DATE "upload_date"
#define FIELD_FILE_PATH "file_path"
